name: SonarCloud Auto Analysis

on:
  push:
    branches: [main, master, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-scan:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    # ADD THIS LINE TO SKIP .GITHUB REPOSITORY:
    if: github.repository != 'Test-talentis/.github'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.organization=Test-talentis
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.github/**